"""
embedding.py
------------
Loads a CLIP model and converts text (captions) into normalized embeddings.

Why CLIP for text-only embeddings?
  CLIP's text encoder produces vectors in the same latent space as its image
  encoder, so in Part 3 we can do image<->text search without re-indexing.

Model used: openai/clip-vit-base-patch32  (lightweight, ~600 MB download)
"""

import numpy as np
import torch
from transformers import CLIPTokenizer, CLIPTextModel

# ---------------------------------------------------------------------------
# Model loading — cached at module level so it loads only once per session.
# ---------------------------------------------------------------------------

MODEL_NAME = "openai/clip-vit-base-patch32"

_tokenizer: CLIPTokenizer | None = None
_model: CLIPTextModel | None = None


def _load_model() -> tuple[CLIPTokenizer, CLIPTextModel]:
    """
    Lazily load and cache the CLIP tokenizer + text encoder.
    Uses CPU by default; CUDA is used automatically if available.
    """
    global _tokenizer, _model

    if _tokenizer is None or _model is None:
        _tokenizer = CLIPTokenizer.from_pretrained(MODEL_NAME)
        _model = CLIPTextModel.from_pretrained(MODEL_NAME)
        _model.eval()  # disable dropout / batch-norm training behaviour

    return _tokenizer, _model


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_text_embedding(text: str) -> np.ndarray:
    """
    Convert a text string into a normalized CLIP embedding vector.

    Steps:
      1. Tokenize the text (truncated to CLIP's 77-token limit).
      2. Run the CLIP text encoder (no gradient tracking needed).
      3. Use the pooled output (shape: [1, 512]).
      4. L2-normalize so dot-product == cosine similarity in FAISS.

    Args:
        text: Any string — typically a caption generated by BLIP.

    Returns:
        A float32 numpy array of shape (512,), unit-normalized.
    """
    tokenizer, model = _load_model()

    # Tokenize — CLIP caps at 77 tokens; truncation=True handles overflow.
    inputs = tokenizer(
        text,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=77,
    )

    with torch.no_grad():
        outputs = model(**inputs)

    # pooler_output: [1, 512]  — the [CLS]-style sentence representation
    embedding = outputs.pooler_output.squeeze(0).cpu().numpy()  # (512,)

    # L2-normalize so IndexFlatIP behaves as cosine similarity
    norm = np.linalg.norm(embedding)
    if norm > 0:
        embedding = embedding / norm

    return embedding.astype(np.float32)